import type { Metadata } from "next";
import "./globals.css";
import AOSWrapper from "@/components/AOSWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    
    <html lang="fr" data-theme="light" >
      <body className="antialiased min-h-screen bg-gray-100/96 ">
        <AOSWrapper />
        {children}
      </body>
    </html>
  );
}
